#!/usr/bin/env node
/**
 * MicaNT Metadata Ingestion & Code Generator
 * Parses Microsoft's win32metadata repository to extract NT system call interfaces,
 * types, and mappings into modern C++23 declarations.
 */

const fs = require('fs');
const path = require('path');

const METADATA_DIR = path.resolve(__dirname, '../../../win32metadata');
const API_CSV = path.join(METADATA_DIR, 'scripts', 'ApiInfo.csv');
const OUTPUT_HEADER = path.resolve(__dirname, '../../include/micant/generated_nt_api.hpp');

console.log('[MicaNT Codegen] Initializing metadata parser...');
console.log(`[MicaNT Codegen] Checking for win32metadata at: ${API_CSV}`);

if (!fs.existsSync(API_CSV)) {
    console.error(`[MicaNT Codegen] Error: ApiInfo.csv not found at ${API_CSV}`);
    process.exit(1);
}

const csvData = fs.readFileSync(API_CSV, 'utf8');
const lines = csvData.split(/\r?\n/);

const ntApis = [];
const rtlApis = [];

console.log(`[MicaNT Codegen] Parsing ${lines.length} API entries from win32metadata...`);

for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    const parts = line.split(',');
    const name = parts[0] || parts[1];
    const header = parts[2] || '';
    const techRoot = parts[3] || '';

    if (!name) continue;

    if (name.startsWith('Nt') || name.startsWith('Zw')) {
        ntApis.push({ name, header, techRoot });
    } else if (name.startsWith('Rtl')) {
        rtlApis.push({ name, header, techRoot });
    }
}

console.log(`[MicaNT Codegen] Found ${ntApis.length} Nt/Zw system calls.`);
console.log(`[MicaNT Codegen] Found ${rtlApis.length} Rtl runtime library routines.`);

// Generate C++23 header
let cppOutput = `// Auto-generated by MicaNT codegen from win32metadata (MIT License)
// Standard: ISO C++23
#pragma once

#include <string_view>
#include <array>
#include <cstdint>

namespace micant::generated {

struct ApiDefinition {
    std::string_view name;
    std::string_view header;
    std::string_view category;
};

inline constexpr std::array<ApiDefinition, ${ntApis.length}> NtSystemCallCatalog = {{
`;

for (const api of ntApis) {
    cppOutput += `    { "${api.name}", "${api.header}", "${api.techRoot}" },\n`;
}

cppOutput += `}};

inline constexpr std::array<ApiDefinition, ${rtlApis.length}> RtlRoutineCatalog = {{
`;

for (const api of rtlApis) {
    cppOutput += `    { "${api.name}", "${api.header}", "${api.techRoot}" },\n`;
}

cppOutput += `}};

} // namespace micant::generated
`;

fs.writeFileSync(OUTPUT_HEADER, cppOutput, 'utf8');
console.log(`[MicaNT Codegen] Successfully emitted ${OUTPUT_HEADER} (${(fs.statSync(OUTPUT_HEADER).size / 1024).toFixed(1)} KB)`);
